---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove: #[]
  - Launchpad
  - TV
  - Podcasts
  - 'App Store'
  - Maps
  - Photos
  - FaceTime
  - Notes
  - Freeform
  - Music
  - Keynote
  - Numbers
  - Pages
dockitems_persist: #[]
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5
- name: "System Settings"
  path: "/Applications/System Settings.app/"
  pos: 1
- name: "Terminal"
  path: "/Applications/Utilities/Terminal.app/"
  pos: 2
- name: "'' --type spacer"
  pos: "--after Terminal"
- name: "Messages"
  path: "/Applications/Messages.app/"
  pos: 3
- name: "Mattermost"
  path: "/Applications/Mattermost.app/"
  pos: 4
- name: "Signal"
  path: "/Applications/Signal.app/"
  pos: 5
- name: "Telegram"
  path: "/Applications/Telegram.app/"
  pos: 6
- name: "'' --type spacer"
  pos: "--after Terminal"
- name: "Applications"
  path: "~/Applications --view list"
  pos: "end"
- name: "Downloads"
  path: "~/Downloads --view list"
  pos: "end"

dotfiles_repo: https://github.com/royvandongen/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .osx
  - .vimrc

homebrew_installed_packages:
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - git
  - iperf
  - nmap
  - ssh-copy-id
  - openssl
  - wget
  - zsh-history-substring-search

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - audacity
  - balenaetcher
  - docker
  - dropbox
  #- enpass Rosetta required
  - firefox
  - google-chrome
  - istat-menus
  - loopback
  - mattermost
  - microsoft-office
  - microsoft-teams
  - mqtt-explorer
  - nextcloud
  - obs
  #- private-internet-access
  - signal
  - spotify
  - sublime-text
  - telegram
  - tidal
  - visual-studio-code
  - vlc
  - wireshark
  #-yt-dlp This fails for a strange reason, but can be installed manually

osx_script: "~/.osx --no-restart"
osx_scriptfile: "~/.osx"

# Set to 'true' to configure Sublime Text.
configure_sublime: true
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "Jinja2"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "Dockerfile Syntax Highlighting"


# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
