---
# TODO: Use sudo once .osx can be run via root with no user interaction.
- name: Set executable bit on osx script
  file:
    dest: "{{ osx_scriptfile }}"
    mode: a+x

- name: Run .osx dotfiles.
  command: "{{ osx_script }}"
  changed_when: false
